/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    extend: {
      colors: {
        primary: "var(--sys-primary)",
        "on-primary": "var(--sys-on-primary)",
        "primary-container": "var(--sys-primary-container)",
        "on-primary-container": "var(--sys-on-primary-container)",
        secondary: "var(--sys-secondary)",
        "on-secondary": "var(--sys-on-secondary)",
        "secondary-container": "var(--sys-secondary-container)",
        "on-secondary-container": "var(--sys-on-secondary-container)",
        tertiary: "var(--sys-tertiary)",
        "on-tertiary": "var(--sys-on-tertiary)",
        "tertiary-container": "var(--sys-tertiary-container)",
        "on-tertiary-container": "var(--sys-on-tertiary-container)",
        error: "var(--sys-error)",
        "on-error": "var(--sys-on-error)",
        "error-container": "var(--sys-error-container)",
        "on-error-container": "var(--sys-on-error-container)",
        background: "var(--sys-background)",
        "on-background": "var(--sys-on-background)",
        surface: "var(--sys-surface)",
        "on-surface": "var(--sys-on-surface)",
        surfaceVariant: "var(--sys-surface-variant)",
        "on-surface": "var(--sys-on-surface-variant)",
        outline: "var(--sys-outline)",
        outlineVariant: "var(--sys-outline-variant)",
        shadow: "var(--sys-shadow)",
        scrim: "var(--sys-scrim)",
        inverseSurface: "var(--sys-inverse-surface)",
        "inverse-on-surface": "var(--sys-inverse-on-surface)",
        inversePrimary: "var(--sys-inverse-primary)",
        primaryFixed: "var(--sys-primary-fixed)",
        "on-primary-fixed": "var(--sys-on-primary-fixed)",
        primaryFixedDim: "var(--sys-primary-fixed-dim)",
        onPrimaryFixedVariant: "var(--sys-on-primary-fixed-variant)",
        secondaryFixed: "var(--sys-secondary-fixed)",
        "on-secondary-fixed": "var(--sys-on-secondary-fixed)",
        secondaryFixedDim: "var(--sys-secondary-fixed-dim)",
        onSecondaryFixedVariant: "var(--sys-on-secondary-fixed-variant)",
        tertiaryFixed: "var(--sys-tertiary-fixed)",
        "on-tertiary-fixed": "var(--sys-on-tertiary-fixed)",
        tertiaryFixedDim: "var(--sys-tertiary-fixed-dim)",
        onTertiaryFixedVariant: "var(--sys-on-tertiary-fixed-variant)",
        surfaceDim: "var(--sys-surface-dim)",
        surfaceBright: "var(--sys-surface-bright)",
        surfaceContainerLowest: "var(--sys-surface-container-lowest)",
        surfaceContainerLow: "var(--sys-surface-container-low)",
        surfaceContainer: "var(--sys-surface-container)",
        surfaceContainerHigh: "var(--sys-surface-container-high)",
        surfaceContainerHighest: "var(--sys-surface-container-highest)",
      },
      backgroundImage: {
        // 'login-bg': "url('/loginPageBackground.jpg')",
        'login-bg': "url('/loginPageBackground.jpg')",
      },
    },
  },
  plugins: [],
};
